# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Release

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create zip with all important files
      run: |
        mkdir setup-zip
        cp example.env setup-zip/.env && cp README.md setup-zip/README.md && target/mcstatus-1.0-SNAPSHOT.jar setup-zip/mcstatus-1.0-SNAPSHOT.jar
        cd setup-zip
        zip -r ../mcstatus-complete.zip .
        cd ..
        rm -rf setup-zip


    - name: Preparing Github Release
      id: new-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{  secrets.GITHUB_TOKEN }}
      with:
        release_name: ${{ github.event.head_commit.message }}
    
    - name: Uploading zip archive
      id: release_zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.new-release.outputs.upload_url }}
        asset_path: ./mcstatus-complete.zip
        asset_name: mcstatus-discord-setup.zip
        asset_content_type: application/zip
        
    - name: Uploading zip archive
      id: release_java
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.new-release.outputs.upload_url }}
        asset_path: ./mcstatus-1.0-SNAPSHOT.jar
        asset_name: mcstatus-1.0-SNAPSHOT.jar
        asset_content_type: application/java-archive
      
